In [2]:
!pip install tensorflow==2.9.1
!pip install tensorflow-hub==0.12.0
!pip install tensorflow-text==2.9.0

  Using cached tensorflow-2.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.7 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.15.1 requires tensorflow<2.16,>=2.15, but you have tensorflow 2.9.1 which is incompatible.
  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
  Using cached tensorflow_text-2.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)


In [3]:
preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [5]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [6]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [7]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [8]:
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [9]:
text_preprocessed['input_mask']

# CLS nice movie indeed SEP
# 128 is max length of the sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [10]:
text_preprocessed['input_type_ids']

# Crucial for more than one sentences if given input

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [11]:
text_preprocessed['input_word_ids']

# CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [12]:
bert_model =  hub.KerasLayer(encoder_url)

bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['sequence_output', 'default', 'encoder_outputs', 'pooled_output'])

In [13]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.21411917,  0.4976954 , ...,  0.24465218,
        -0.47334483,  0.8175871 ],
       [-0.9171231 , -0.4793517 , -0.7865698 , ..., -0.6175175 ,
        -0.71026856,  0.92184293]], dtype=float32)>

In [14]:
bert_results['sequence_output']

# nice movie indeed 0 0 0 0 0 0 0 0  <----- 128

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292042,  0.0856783 ,  0.14476834, ..., -0.09677099,
          0.08722139,  0.07711082],
        [ 0.17839429, -0.19006051,  0.503494  , ..., -0.05869813,
          0.32717112, -0.15578538],
        [ 0.18701534, -0.43388787, -0.48875102, ..., -0.15502812,
          0.0014514 , -0.24470966],
        ...,
        [ 0.12083082,  0.12884255,  0.46453565, ...,  0.07375513,
          0.17441949,  0.16522074],
        [ 0.07967876, -0.0119067 ,  0.50225437, ...,  0.13777758,
          0.210022  ,  0.00624586],
        [-0.07212726, -0.2830349 ,  0.5903336 , ...,  0.4755189 ,
          0.16668434, -0.08920301]],

       [[-0.07900558,  0.36335093, -0.21101578, ..., -0.17183772,
          0.16299748,  0.6724267 ],
        [ 0.27883533,  0.4371628 , -0.35764763, ..., -0.04463646,
          0.38315225,  0.5887989 ],
        [ 1.2037673 ,  1.072702  ,  0.48408782, ...,  0.24921028,
          0.40730938,  0.40481862],
        ...,

In [15]:
len(bert_results['encoder_outputs'])

# Output of each individual encoder, since we have 12 encoders in bert basic version

12

In [16]:
bert_results['encoder_outputs']

[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901422,  0.00644744, -0.03614965, ...,  0.0499962 ,
           0.06149198, -0.02657532],
         [ 1.1753383 ,  1.2140785 ,  1.156998  , ...,  0.1163438 ,
          -0.35855362, -0.40490192],
         [ 0.03859013,  0.53869987, -0.21089762, ...,  0.21858196,
           0.7260165 , -1.1158605 ],
         ...,
         [-0.07587016, -0.25421906,  0.7075512 , ...,  0.50541985,
          -0.18878691,  0.15028355],
         [-0.16066596, -0.2808967 ,  0.5759707 , ...,  0.5275854 ,
          -0.11141396,  0.02887552],
         [-0.04428156, -0.20279594,  0.5909356 , ...,  0.81338346,
          -0.39075798, -0.02601732]],
 
        [[ 0.18903592,  0.02752544, -0.06513739, ..., -0.00620209,
           0.15053897,  0.0316545 ],
         [ 0.5916149 ,  0.75891405, -0.0724066 , ...,  0.6190398 ,
           0.829289  ,  0.16161948],
         [ 1.4460826 ,  0.44602674,  0.40990263, ...,  0.48255908,
           0.62691134,  0.13

In [17]:
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>